version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: kd
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: dino
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: kd
      MARIADB_DATABASE: dino
      MARIADB_PASSWORD: 1234

volumes:
  wordpress:
